### ISSUE TITLE
Test - extended attributes

### ISSUE THREAD

**Issue by adorton-adobe** [adorton-adobe/user-sync.py#23]
Mock a response w/ extra attributes and ensure that the extended attribute functionality is able to expose them to the consumer of the Okta connector.

**Comment by shasibhusanJena** [comment]
as part of this it, test case will cover calling of function  iter_group_members() which internally calls find_group() and OKTAValueFormatter.get_extended_attribute_dict() and groups_client.get_group_all_users()

respectively .
