### ISSUE TITLE
Load Testing Okta Connector

### ISSUE THREAD

**Issue by bhunut-adobe** [adorton-adobe/user-sync.py#28]
Test performance of Okta user API on 10k Users

**Comment by bhunut-adobe** [comment]
Found issue #29

**Comment by bhunut-adobe** [comment]
Due to Limitation of Okta Preview instant. We can only provision up to 1000 activate user accounts.

During this test, it takes 16-20sec to retrieve 1000 users from the API

**Comment by adorton-adobe** [comment]
Are we ready to close this issue?  If not, what more do we need to do?
