### ISSUE TITLE
Okta SDK limited # of result it returned

### ISSUE THREAD

**Issue by bhunut-adobe** [adorton-adobe/user-sync.py#29]
Okta SDK limited the result to 200

**Comment by adorton-adobe** [comment]
Does the API have a pagination mechanism?

**Comment by bhunut-adobe** [comment]
API supported by using "after" parameter but it is not implemented in the SDK.

http://developer.okta.com/docs/api/resources/users.html#list-users
http://developer.okta.com/docs/api/getting_started/design_principles.html#pagination

**Comment by adorton-adobe** [comment]
That's frustrating.  Let's update the SDK.

**Comment by bhunut-adobe** [comment]
Sorry, It is implemented in the SDK as get_paged_users() which return PagedResults object that contained the next URL to be used for the next set of results.

However groupclient class does not provide get_paged_group_users(). This has to be implemented.

**Comment by bhunut-adobe** [comment]
I put in a ticket with Okta regarding issue with Paginate on getting Group users.

**Comment by adorton-adobe** [comment]
Thanks @bhunut-adobe - please create a separate issue to keep track of it.  Include any correspondence with Okta and a ticket #/CRM link if you have one.

**Comment by bhunut-adobe** [comment]
Okta SDK updated. Need to refactoring directory_okta.py to use new methods
