### ISSUE TITLE
Review v2 changes and test compatibility of Okta functionality

### ISSUE THREAD

**Issue by adorton-adobe** [adorton-adobe/user-sync.py#36]
The upstream repo now has a [v2](https://github.com/adobe-apiplatform/user-sync.py/tree/v2) branch for new changes related to 2.0.  I've merged to my local copy of our `okta` branch and I'm in the process of reviewing the changes.

Once review is complete, we need to test our okta updates to make sure nothing has broken.

**Comment by bhunut-adobe** [comment]
Resolved issue #37 and #38 related to V2 changes. Basic functionality is working, I haven't tested the new feature yet

**Comment by adorton-adobe** [comment]
Can you please submit a PR when you're ready?

**Comment by adorton-adobe** [comment]
I think we're good here.  I've tested a few scenarios and haven't found any issues.
